# Generated by Django 4.2 on 2023-04-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizes", "0003_remove_deliveredquizmcqs_quiz_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveredquiz",
            name="total_numbers",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
