# Generated by Django 4.2 on 2023-04-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizes", "0004_alter_deliveredquiz_total_numbers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizmcqs",
            name="question",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="quizpythonproblem",
            name="question",
            field=models.TextField(),
        ),
    ]
