# Generated by Django 4.2 on 2023-04-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizes", "0009_deliveredquizpython"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveredquizpython",
            name="answer",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
