# Generated by Django 4.2 on 2023-04-23 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_remove_course_quiz_course_quiz"),
        ("quizes", "0011_alter_deliveredquizpython_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveredquiz",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
            ),
        ),
    ]
