# Generated by Django 4.2 on 2023-04-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizes", "0014_alter_quizpythonproblem_correct_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizpythonproblem",
            name="correct_answer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
