# Generated by Django 4.2 on 2023-05-13 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quizes", "0020_alter_deliveredquiz_quiz"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quizmcqs",
            old_name="numbers",
            new_name="total_numbers",
        ),
        migrations.RemoveField(
            model_name="quizmcqs",
            name="correct_answer",
        ),
        migrations.CreateModel(
            name="McqsCorrectAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numbers", models.FloatField()),
                ("correct_answer", models.CharField(max_length=255)),
                (
                    "mcqs",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quizes.quizmcqs",
                    ),
                ),
            ],
        ),
    ]
