# Generated by Django 4.2 on 2023-05-14 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quizes", "0023_alter_mcqscorrectanswer_correct_answer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deliveredquizmcqs",
            old_name="numbers",
            new_name="total_number",
        ),
        migrations.RemoveField(
            model_name="deliveredquizmcqs",
            name="answer",
        ),
        migrations.RemoveField(
            model_name="deliveredquizmcqs",
            name="is_correct_answer",
        ),
        migrations.CreateModel(
            name="DeliveredMcqsAnswers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(max_length=255)),
                ("is_correct_answer", models.BooleanField(max_length=255)),
                (
                    "delivered_mcqs_quiz",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quizes.deliveredquizmcqs",
                    ),
                ),
            ],
        ),
    ]
