# Generated by Django 4.2 on 2023-04-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="courses/"),
        ),
    ]
