# Generated by Django 4.2 on 2023-04-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0001_initial"),
        ("courses", "0005_remove_course_quiz_course_quiz"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="students",
        ),
        migrations.AddField(
            model_name="course",
            name="classes",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="classes.class"
            ),
        ),
    ]
