# Generated by Django 4.2 on 2023-05-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_coursefile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursefile",
            name="file",
            field=models.FileField(upload_to="courses/"),
        ),
    ]
