# Generated by Django 4.2 on 2023-04-10 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="QuizPythonProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("numbers", models.FloatField()),
                ("correct_answer", models.CharField(max_length=255)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quizes.quiz"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizPythonProblemTestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("numbers", models.FloatField()),
                ("correct_answer", models.CharField(max_length=255)),
                (
                    "quiz_python_problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quizes.quizpythonproblem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizMcqs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("option1", models.CharField(blank=True, max_length=255, null=True)),
                ("option2", models.CharField(blank=True, max_length=255, null=True)),
                ("option3", models.CharField(blank=True, max_length=255, null=True)),
                ("option4", models.CharField(blank=True, max_length=255, null=True)),
                ("numbers", models.FloatField()),
                ("correct_answer", models.CharField(max_length=255)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quizes.quiz"
                    ),
                ),
            ],
        ),
    ]
