# Generated by Django 4.2 on 2023-04-15 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quizes", "0002_deliveredquizmcqs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveredquizmcqs",
            name="quiz",
        ),
        migrations.RemoveField(
            model_name="deliveredquizmcqs",
            name="student",
        ),
        migrations.CreateModel(
            name="DeliveredQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_numbers", models.FloatField()),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quizes.quiz"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="deliveredquizmcqs",
            name="delivered_quiz",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quizes.deliveredquiz",
            ),
        ),
    ]
