# Generated by Django 4.2 on 2023-04-20 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quizes", "0006_alter_quizmcqs_quiz_alter_quizpythonproblem_quiz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizpythonproblemtestcase",
            name="quiz_python_problem",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quizes.quizpythonproblem",
            ),
        ),
    ]
