# Generated by Django 4.2 on 2023-04-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizes", "0007_alter_quizpythonproblemtestcase_quiz_python_problem"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizpythonproblem",
            name="sample_code",
            field=models.TextField(null=True),
        ),
    ]
