# Generated by Django 4.2 on 2023-04-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizes", "0010_alter_deliveredquizpython_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveredquizpython",
            name="numbers",
            field=models.FloatField(null=True),
        ),
    ]
