# Generated by Django 4.2 on 2023-04-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizes", "0012_deliveredquiz_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizpythonproblemtestcase",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
