# Generated by Django 4.2 on 2023-05-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizes", "0018_deliveredquizpython_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveredquiz",
            name="is_custom_add",
            field=models.BooleanField(default=False),
        ),
    ]
