# Generated by Django 4.2 on 2023-05-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizes", "0021_rename_numbers_quizmcqs_total_numbers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcqscorrectanswer",
            name="correct_answer",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
