# Generated by Django 4.2 on 2023-05-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizes", "0022_alter_mcqscorrectanswer_correct_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcqscorrectanswer",
            name="correct_answer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
